# -*- coding: utf-8 -*-
"""ckassification_bank_transactions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HnUEpBXpuuOrEg-2pu2Nf9Ssw6AEJIjd
"""

import polars as pl
import pandas as pd
from catboost import CatBoostClassifier, Pool
import datetime
import gc
import numpy as np
import os
from gensim.models import Word2Vec
from sklearn.metrics import average_precision_score

# ==========================================
# 1. КОНФИГУРАЦИЯ И ПУТИ
# ==========================================
# Укажите здесь актуальные пути к вашим данным
PRETRAIN_FILES = [f"/content/drive/MyDrive/хакатон3/pretrain_part_{i}.parquet" for i in range(1, 4)]
TRAIN_FILES = [f"/content/drive/MyDrive/хакатон3/train_part_{i}.parquet" for i in range(1, 4)]
TRAIN_LABELS = "/content/drive/MyDrive/хакатон3/train_labels.parquet"
PRETEST_FILE = "/content/drive/MyDrive/хакатон3/pretest.parquet"
TEST_FILE = "/content/drive/MyDrive/хакатон3/test.parquet"

def log_step(msg):
    """Утилита для логирования этапов выполнения."""
    print(f"[{datetime.datetime.now().strftime('%H:%M:%S')}]  🔹  {msg}")

def get_history_lazy(files):
    """Ленивое чтение истории транзакций для экономии памяти."""
    return pl.scan_parquet(files).select([
        "customer_id", "operaton_amt", "event_id", "event_dttm", "mcc_code", "device_system_version"
    ]).unique(subset=["event_id"], maintain_order=True).with_columns([
        pl.col("mcc_code").fill_null("-1").cast(pl.String),
        pl.col("device_system_version").fill_null("UNK").cast(pl.String)
    ])

# ==========================================
# 2. ГЕНЕРАЦИЯ ЭМБЕДДИНГОВ (WORD2VEC)
# ==========================================
def train_mcc_word2vec(vector_size=32):
    log_step("Генерация токенов (MCC + Сумма + Время)...")
    hist_lazy = pl.concat([get_history_lazy(PRETRAIN_FILES), get_history_lazy(TRAIN_FILES)])

    hist_tokens_df = hist_lazy.with_columns([
        pl.col("event_dttm").str.to_datetime().dt.hour().alias("hour"),
        pl.col("operaton_amt").fill_null(0).cast(pl.Float32)
    ]).with_columns([
        (pl.col("hour") // 6).cast(pl.String).alias("time_bin"),
        pl.col("operaton_amt").log1p().cast(pl.Int32).cast(pl.String).alias("amt_bin")
    ]).with_columns([
        pl.concat_str([pl.col("mcc_code"), pl.col("amt_bin"), pl.col("time_bin")], separator="_").alias("complex_token")
    ]).select(["customer_id", "complex_token", "event_dttm"]).collect()

    hist_tokens_df = hist_tokens_df.sort(["customer_id", "event_dttm"])
    sentences = hist_tokens_df.group_by("customer_id", maintain_order=True).agg(pl.col("complex_token"))["complex_token"].to_list()

    log_step(f"Обучение Word2Vec (размер вектора: {vector_size})...")
    w2v_model = Word2Vec(sentences, vector_size=vector_size, window=7, min_count=1, workers=4, sg=1, negative=7, epochs=5, seed=42)
    vocab = list(w2v_model.wv.index_to_key)
    vectors = [w2v_model.wv[word] for word in vocab]
    del sentences; gc.collect()

    w2v_cols = [f"token_w2v_{i}" for i in range(vector_size)]
    w2v_df = pl.DataFrame({
        "complex_token": vocab,
        **{w2v_cols[i]: [float(v[i]) for v in vectors] for i in range(vector_size)}
    }).select([pl.col("complex_token")] + [pl.col(c).cast(pl.Float32) for c in w2v_cols])

    user_w2v_cols = [f"user_profile_w2v_{i}" for i in range(vector_size)]
    user_profile_df = hist_tokens_df.lazy().join(w2v_df.lazy(), on="complex_token", how="inner").group_by("customer_id").agg([
        pl.col(w2v_cols[i]).mean().cast(pl.Float32).alias(user_w2v_cols[i]) for i in range(vector_size)
    ]).collect()
    del hist_tokens_df; gc.collect()

    return w2v_df.lazy(), w2v_cols, user_profile_df.lazy(), user_w2v_cols

# ==========================================
# 3. ИНЖЕНЕРИЯ ПРИЗНАКОВ (POLARS)
# ==========================================
def prepare_features_full(df_lazy, hist_stats_lazy, hist_mcc_lazy, hist_device_lazy, w2v_lazy, user_profile_lazy, vector_size=32):
    df_lazy = df_lazy.with_columns([
        pl.col("operaton_amt").is_null().cast(pl.Int8).alias("is_non_financial"),
        pl.col("mcc_code").fill_null("-1").cast(pl.String),
        pl.col("device_system_version").fill_null("UNK").cast(pl.String),
        pl.col("event_dttm").str.to_datetime().alias("event_dttm_dt"),
        pl.col("operaton_amt").cast(pl.Float32).fill_null(0)
    ]).with_columns([
        (pl.col("event_dttm_dt").dt.hour() // 6).cast(pl.String).alias("time_bin"),
        pl.col("operaton_amt").log1p().cast(pl.Int32).cast(pl.String).alias("amt_bin")
    ]).with_columns([
        pl.concat_str([pl.col("mcc_code"), pl.col("amt_bin"), pl.col("time_bin")], separator="_").alias("complex_token")
    ])

    df_joined = df_lazy.join(hist_stats_lazy, on="customer_id", how="left")
    df_joined = df_joined.join(hist_mcc_lazy, on=["customer_id", "mcc_code"], how="left")
    df_joined = df_joined.join(hist_device_lazy, on=["customer_id", "device_system_version"], how="left")
    df_joined = df_joined.join(w2v_lazy, on="complex_token", how="left")
    df_joined = df_joined.join(user_profile_lazy, on="customer_id", how="left")

    dot_expr = pl.sum_horizontal([pl.col(f"token_w2v_{i}").fill_null(0) * pl.col(f"user_profile_w2v_{i}").fill_null(0) for i in range(vector_size)])
    norm_tok_expr = pl.sum_horizontal([pl.col(f"token_w2v_{i}").fill_null(0)**2 for i in range(vector_size)]).sqrt()
    norm_usr_expr = pl.sum_horizontal([pl.col(f"user_profile_w2v_{i}").fill_null(0)**2 for i in range(vector_size)]).sqrt()

    df_joined = df_joined.with_columns([(dot_expr / (norm_tok_expr * norm_usr_expr + 1e-6)).cast(pl.Float32).alias("w2v_cosine_similarity")])
    df_joined = df_joined.with_columns(
        [pl.col(f"token_w2v_{i}").fill_null(0).cast(pl.Float32) for i in range(vector_size)] +
        [pl.col(f"user_profile_w2v_{i}").fill_null(0).cast(pl.Float32) for i in range(vector_size)]
    )

    return (
        df_joined
        .with_columns([
            pl.col("last_hist_dttm").str.to_datetime().alias("last_hist_dttm_dt"),
            pl.col("user_mcc_count").fill_null(0).cast(pl.Int32),
            pl.col("user_device_count").fill_null(0).cast(pl.Int32),
            (pl.col("device_system_version") == "UNK").cast(pl.Int8).alias("is_device_missing"),
            pl.col("user_median_hour").fill_null(12).cast(pl.Float32),
        ])
        .sort(["customer_id", "event_dttm_dt"])
        .with_columns([
            pl.col("event_type_nm").fill_null("UNK").cast(pl.String),
            pl.col("event_desc").fill_null("UNK").cast(pl.String),
            pl.col("channel_indicator_type").fill_null("UNK").cast(pl.String),
            pl.col("channel_indicator_sub_type").fill_null("UNK").cast(pl.String),
            pl.col("pos_cd").fill_null("UNK").cast(pl.String),
            pl.col("operating_system_type").fill_null("UNK").cast(pl.String),
            pl.col("timezone").fill_null("UNK").cast(pl.String),
            pl.col("phone_voip_call_state").fill_null(0).cast(pl.Int8),
            pl.col("developer_tools").cast(pl.String).fill_null("UNK"),
            pl.col("web_rdp_connection").cast(pl.String).fill_null("UNK"),
            pl.col("compromised").cast(pl.String).fill_null("UNK"),
            pl.col("screen_size").str.split("x").list.get(0).cast(pl.Float32, strict=False).fill_null(0).alias("screen_w"),
            pl.col("event_dttm_dt").dt.hour().cast(pl.Int8).alias("hour"),
            pl.col("event_dttm_dt").dt.weekday().cast(pl.Int8).alias("day_of_week"),
            pl.concat_str([pl.col("mcc_code"), pl.lit("_"), pl.col("event_desc")]).alias("mcc_event_desc"),
            pl.concat_str([pl.col("mcc_code"), pl.lit("_"), pl.col("device_system_version")]).alias("mcc_device"),
            pl.col("operaton_amt").log1p().alias("operaton_amt_log"),
            (pl.col("event_dttm_dt").dt.hour() < 6).cast(pl.Int8).alias("is_night_transaction"),
            (pl.col("timezone") != pl.col("timezone").shift(1).over("customer_id")).cast(pl.Int8).fill_null(0).alias("is_timezone_changed"),
            pl.col("event_dttm_dt").diff().dt.total_seconds().over("customer_id").alias("diff_internal"),
            (pl.col("operaton_amt").cum_sum().over("customer_id") / pl.col("operaton_amt").cum_count().over("customer_id")).cast(pl.Float32).fill_null(0).alias("user_avg_amt"),
            (pl.col("user_mcc_count") == 0).cast(pl.Int8).alias("is_new_mcc"),
            (pl.col("user_device_count") == 0).cast(pl.Int8).alias("is_new_device"),
        ])
        .with_columns([
            pl.when(pl.col("diff_internal").is_null())
            .then((pl.col("event_dttm_dt") - pl.col("last_hist_dttm_dt")).dt.total_seconds())
            .otherwise(pl.col("diff_internal"))
            .fill_null(999999).cast(pl.Float32).alias("sec_since_last")
        ])
        .with_columns([
            (pl.col("operaton_amt") / (pl.col("sec_since_last") + 1)).cast(pl.Float32).alias("amt_per_sec"),
            (pl.col("operaton_amt") / (pl.col("old_avg_amt") + 1)).cast(pl.Float32).alias("amt_ratio_old"),
            (pl.col("operaton_amt") / (pl.col("user_avg_amt") + 1)).cast(pl.Float32).alias("amt_ratio_user"),
            (pl.col("operaton_amt") / (pl.col("old_max_amt") + 1)).cast(pl.Float32).alias("amt_ratio_max"),
            (pl.col("event_dttm_dt").dt.hour() - pl.col("user_median_hour")).abs().cast(pl.Float32).fill_null(0).alias("hour_diff_from_median"),
            ((pl.col("user_device_count") == 0) & (pl.col("sec_since_last") < 300)).cast(pl.Int8).alias("is_fast_new_device"),
            ((pl.col("user_mcc_count") == 0) & (pl.col("operaton_amt") > pl.col("old_avg_amt") * 3)).cast(pl.Int8).alias("is_large_new_mcc"),
        ])
    )

# ==========================================
# 4. БЛЕНДИНГ (АНСАМБЛИРОВАНИЕ)
# ==========================================
def blend_predictions(catboost_file="submission_catboost_champion.csv", other_file="submission_lightgbm.csv"):
    if not os.path.exists(other_file):
        log_step(f"Файл {other_file} не найден. Пропускаем блендинг.")
        return

    log_step(f"Смешиваем {catboost_file} и {other_file}...")
    sub1 = pd.read_csv(catboost_file)
    sub2 = pd.read_csv(other_file)

    sub1 = sub1.sort_values('event_id').reset_index(drop=True)
    sub2 = sub2.sort_values('event_id').reset_index(drop=True)

    blend = sub1.copy()

    # Взвешенное среднее (CatBoost 60% / Другая модель 40%)
    blend['predict'] = (sub1['predict'] * 0.6) + (sub2['predict'] * 0.4)

    output_name = "submission_final_blend.csv"
    blend.to_csv(output_name, index=False)
    log_step(f"✅ Успешно смешали! Файл сохранен как {output_name}.")

# ==========================================
# 5. ОСНОВНОЙ ПАЙПЛАЙН (MAIN)
# ==========================================
def main():
    w2v_lazy, w2v_cols, user_profile_lazy, user_w2v_cols = train_mcc_word2vec(vector_size=32)

    features = [
        "operaton_amt", "operaton_amt_log", "amt_per_sec", "amt_ratio_old", "amt_ratio_user",
        "amt_ratio_max", "user_mcc_count", "user_device_count", "is_new_mcc", "is_new_device",
        "hour", "day_of_week", "screen_w", "phone_voip_call_state", "developer_tools",
        "web_rdp_connection", "compromised", "sec_since_last", "user_avg_amt", "old_avg_amt",
        "old_max_amt", "old_trans_count", "is_non_financial", "is_device_missing",
        "is_night_transaction", "is_timezone_changed", "event_type_nm", "event_desc",
        "channel_indicator_type", "channel_indicator_sub_type", "mcc_code", "pos_cd",
        "operating_system_type", "device_system_version", "timezone", "mcc_event_desc", "mcc_device",
        "user_median_hour", "hour_diff_from_median", "is_fast_new_device", "is_large_new_mcc",
        "w2v_cosine_similarity"
    ] + w2v_cols + user_w2v_cols

    cat_features = [
        "event_type_nm", "event_desc", "channel_indicator_type", "channel_indicator_sub_type",
        "mcc_code", "pos_cd", "operating_system_type", "device_system_version", "timezone",
        "mcc_event_desc", "mcc_device", "developer_tools", "web_rdp_connection", "compromised"
    ]

    log_step("Шаг 1: Агрегация истории...")
    hist_lazy_train = get_history_lazy(PRETRAIN_FILES)
    hist_stats_train = hist_lazy_train.group_by("customer_id").agg([
        pl.col("operaton_amt").mean().cast(pl.Float32).alias("old_avg_amt"),
        pl.col("operaton_amt").max().cast(pl.Float32).alias("old_max_amt"),
        pl.col("event_id").len().cast(pl.Int32).alias("old_trans_count"),
        pl.col("event_dttm").max().alias("last_hist_dttm"),
        pl.col("event_dttm").str.to_datetime().dt.hour().median().cast(pl.Float32).alias("user_median_hour")
    ]).collect()
    hist_mcc_train = hist_lazy_train.group_by(["customer_id", "mcc_code"]).agg(pl.len().cast(pl.Int32).alias("user_mcc_count")).collect()
    hist_device_train = hist_lazy_train.group_by(["customer_id", "device_system_version"]).agg(pl.len().cast(pl.Int32).alias("user_device_count")).collect()

    log_step("Шаг 2: Подготовка Train...")
    train_dfs = []
    for file_path in TRAIN_FILES:
        chunk_lazy = pl.scan_parquet(file_path).unique(subset=["event_id"], maintain_order=True).join(
            pl.scan_parquet(TRAIN_LABELS).unique(subset=["event_id"], maintain_order=True), on="event_id", how="left"
        )
        chunk_features = prepare_features_full(
            chunk_lazy, hist_stats_train.lazy(), hist_mcc_train.lazy(), hist_device_train.lazy(),
            w2v_lazy, user_profile_lazy, vector_size=32
        ).with_columns([pl.col("target").fill_null(-1).alias("target_orig")])

        chunk_collected = chunk_features.filter(
            (pl.col("target_orig") != -1) | (pl.col("event_id").hash(seed=42) % 100 < 8)
        ).collect().with_columns([
            pl.when(pl.col("target_orig") == 1).then(1.0).otherwise(0.0).alias("target_bin")
        ]).fill_null(0).sort("event_dttm")
        train_dfs.append(chunk_collected)
        gc.collect()

    train_df = pl.concat(train_dfs).sort("event_dttm")
    del train_dfs; gc.collect()

    split_idx = int(len(train_df) * 0.8)
    train_pd = train_df.select(features + ["target_bin"]).to_pandas()
    del train_df; gc.collect()

    X_train = train_pd.iloc[:split_idx].drop(columns=["target_bin"])
    y_train = train_pd.iloc[:split_idx]["target_bin"]
    X_val = train_pd.iloc[split_idx:].drop(columns=["target_bin"])
    y_val = train_pd.iloc[split_idx:]["target_bin"]

    for col in cat_features:
        X_train[col] = X_train[col].astype('category')
        X_val[col] = X_val[col].astype('category')

    train_pool = Pool(data=X_train, label=y_train, cat_features=cat_features)
    val_pool = Pool(data=X_val, label=y_val, cat_features=cat_features)
    del X_train, y_train; gc.collect()

    log_step("Подготовка Теста...")
    hist_lazy_test = pl.concat([get_history_lazy(PRETRAIN_FILES), get_history_lazy(TRAIN_FILES), get_history_lazy(PRETEST_FILE)])
    hist_stats_test = hist_lazy_test.group_by("customer_id").agg([
        pl.col("operaton_amt").mean().cast(pl.Float32).alias("old_avg_amt"),
        pl.col("operaton_amt").max().cast(pl.Float32).alias("old_max_amt"),
        pl.col("event_id").len().cast(pl.Int32).alias("old_trans_count"),
        pl.col("event_dttm").max().alias("last_hist_dttm"),
        pl.col("event_dttm").str.to_datetime().dt.hour().median().cast(pl.Float32).alias("user_median_hour")
    ]).collect()
    hist_mcc_test = hist_lazy_test.group_by(["customer_id", "mcc_code"]).agg(pl.len().cast(pl.Int32).alias("user_mcc_count")).collect()
    hist_device_test = hist_lazy_test.group_by(["customer_id", "device_system_version"]).agg(pl.len().cast(pl.Int32).alias("user_device_count")).collect()

    test_df_polars = prepare_features_full(
        pl.scan_parquet(TEST_FILE).unique(subset=["event_id"], maintain_order=True),
        hist_stats_test.lazy(), hist_mcc_test.lazy(), hist_device_test.lazy(),
        w2v_lazy, user_profile_lazy, vector_size=32
    ).collect().fill_null(0)

    test_event_ids = test_df_polars["event_id"].to_numpy()
    X_test = test_df_polars.select(features).to_pandas()
    del test_df_polars; gc.collect()

    for col in cat_features:
        X_test[col] = X_test[col].astype('category')

    log_step("🔥 ОБУЧЕНИЕ CATBOOST...")
    model_cb = CatBoostClassifier(
        iterations=3500,
        learning_rate=0.03,
        depth=7,
        l2_leaf_reg=5,
        eval_metric='PRAUC',
        task_type="GPU",
        early_stopping_rounds=300,
        verbose=200,
        scale_pos_weight=5.0,
        bagging_temperature=1.0,
        random_seed=42
    )

    model_cb.fit(train_pool, eval_set=val_pool)

    log_step("Расчет метрики...")
    val_preds = model_cb.predict_proba(X_val)[:, 1]
    local_pr_auc = average_precision_score(y_val, val_preds)
    log_step(f"🎯 ИТОГОВЫЙ ЛОКАЛЬНЫЙ PR-AUC: {local_pr_auc:.6f}")

    log_step("Предсказание на Test...")
    final_preds = model_cb.predict_proba(X_test)[:, 1]
    catboost_submission_file = "submission_catboost.csv"
    pd.DataFrame({"event_id": test_event_ids, "predict": final_preds}).to_csv(catboost_submission_file, index=False)
    log_step(f"✅ Файл {catboost_submission_file} создан.")


if __name__ == "__main__":
    main()
